// Dati marche — caricati staticamente, nessuna chiamata al server necessaria
const BRANDS = {
  auto: [
    { nome: "Abarth",        subito: "abarth",        autoscout: "abarth" },
    { nome: "Alfa Romeo",    subito: "alfa-romeo",    autoscout: "alfa-romeo" },
    { nome: "Alpine",        subito: "alpine",        autoscout: "alpine" },
    { nome: "Aston Martin",  subito: "aston-martin",  autoscout: "aston-martin" },
    { nome: "Audi",          subito: "audi",          autoscout: "audi" },
    { nome: "Bentley",       subito: "bentley",       autoscout: "bentley" },
    { nome: "BMW",           subito: "bmw",           autoscout: "bmw" },
    { nome: "BYD",           subito: "byd",           autoscout: "byd" },
    { nome: "Chevrolet",     subito: "chevrolet",     autoscout: "chevrolet" },
    { nome: "Citroën",       subito: "citroen",       autoscout: "citroen" },
    { nome: "Cupra",         subito: "cupra",         autoscout: "cupra" },
    { nome: "Dacia",         subito: "dacia",         autoscout: "dacia" },
    { nome: "DS Automobiles",subito: "ds",            autoscout: "ds-automobiles" },
    { nome: "Ferrari",       subito: "ferrari",       autoscout: "ferrari" },
    { nome: "Fiat",          subito: "fiat",          autoscout: "fiat" },
    { nome: "Ford",          subito: "ford",          autoscout: "ford" },
    { nome: "Honda",         subito: "honda",         autoscout: "honda" },
    { nome: "Hyundai",       subito: "hyundai",       autoscout: "hyundai" },
    { nome: "Infiniti",      subito: "infiniti",      autoscout: "infiniti" },
    { nome: "Jaguar",        subito: "jaguar",        autoscout: "jaguar" },
    { nome: "Jeep",          subito: "jeep",          autoscout: "jeep" },
    { nome: "Kia",           subito: "kia",           autoscout: "kia" },
    { nome: "Lamborghini",   subito: "lamborghini",   autoscout: "lamborghini" },
    { nome: "Lancia",        subito: "lancia",        autoscout: "lancia" },
    { nome: "Land Rover",    subito: "land-rover",    autoscout: "land-rover" },
    { nome: "Lexus",         subito: "lexus",         autoscout: "lexus" },
    { nome: "Maserati",      subito: "maserati",      autoscout: "maserati" },
    { nome: "Mazda",         subito: "mazda",         autoscout: "mazda" },
    { nome: "Mercedes-Benz", subito: "mercedes",      autoscout: "mercedes-benz" },
    { nome: "MG",            subito: "mg",            autoscout: "mg" },
    { nome: "Mini",          subito: "mini",          autoscout: "mini" },
    { nome: "Mitsubishi",    subito: "mitsubishi",    autoscout: "mitsubishi" },
    { nome: "Nissan",        subito: "nissan",        autoscout: "nissan" },
    { nome: "Opel",          subito: "opel",          autoscout: "opel" },
    { nome: "Peugeot",       subito: "peugeot",       autoscout: "peugeot" },
    { nome: "Polestar",      subito: "polestar",      autoscout: "polestar" },
    { nome: "Porsche",       subito: "porsche",       autoscout: "porsche" },
    { nome: "Renault",       subito: "renault",       autoscout: "renault" },
    { nome: "Rolls-Royce",   subito: "rolls-royce",   autoscout: "rolls-royce" },
    { nome: "Seat",          subito: "seat",          autoscout: "seat" },
    { nome: "Skoda",         subito: "skoda",         autoscout: "skoda" },
    { nome: "Smart",         subito: "smart",         autoscout: "smart" },
    { nome: "Subaru",        subito: "subaru",        autoscout: "subaru" },
    { nome: "Suzuki",        subito: "suzuki",        autoscout: "suzuki" },
    { nome: "Tesla",         subito: "tesla",         autoscout: "tesla" },
    { nome: "Toyota",        subito: "toyota",        autoscout: "toyota" },
    { nome: "Volkswagen",    subito: "volkswagen",    autoscout: "volkswagen" },
    { nome: "Volvo",         subito: "volvo",         autoscout: "volvo" },
  ],
  moto: [
    { nome: "Aprilia",          subito: "aprilia",         autoscout: "aprilia",         motoIt: "aprilia" },
    { nome: "Benelli",          subito: "benelli",         autoscout: "benelli",         motoIt: "benelli" },
    { nome: "Beta",             subito: "beta",            autoscout: "beta",            motoIt: "betamotor" },
    { nome: "BMW",              subito: "bmw",             autoscout: "bmw",             motoIt: "bmw" },
    { nome: "CFMOTO",           subito: "cfmoto",          autoscout: "cfmoto",          motoIt: "cfmoto" },
    { nome: "Ducati",           subito: "ducati",          autoscout: "ducati",          motoIt: "ducati" },
    { nome: "Fantic",           subito: "fantic",          autoscout: "fantic",          motoIt: "fantic-motor" },
    { nome: "Gas Gas",          subito: "gas-gas",         autoscout: "gas-gas",         motoIt: "gasgas" },
    { nome: "Harley-Davidson",  subito: "harley-davidson", autoscout: "harley-davidson", motoIt: "harley-davidson" },
    { nome: "Honda",            subito: "honda",           autoscout: "honda",           motoIt: "honda" },
    { nome: "Husqvarna",        subito: "husqvarna",       autoscout: "husqvarna",       motoIt: "husqvarna" },
    { nome: "Indian",           subito: "indian",          autoscout: "indian",          motoIt: "indian" },
    { nome: "Kawasaki",         subito: "kawasaki",        autoscout: "kawasaki",        motoIt: "kawasaki" },
    { nome: "KTM",              subito: "ktm",             autoscout: "ktm",             motoIt: "ktm" },
    { nome: "Kymco",            subito: "kymco",           autoscout: "kymco",           motoIt: "kymco" },
    { nome: "Moto Guzzi",       subito: "moto-guzzi",      autoscout: "moto-guzzi",      motoIt: "moto-guzzi" },
    { nome: "MV Agusta",        subito: "mv-agusta",       autoscout: "mv-agusta",       motoIt: "mv-agusta" },
    { nome: "Piaggio",          subito: "piaggio",         autoscout: "piaggio",         motoIt: "piaggio" },
    { nome: "Royal Enfield",    subito: "royal-enfield",   autoscout: "royal-enfield",   motoIt: "royal-enfield" },
    { nome: "Sherco",           subito: "sherco",          autoscout: "sherco",          motoIt: "sherco" },
    { nome: "Suzuki",           subito: "suzuki",          autoscout: "suzuki",          motoIt: "suzuki" },
    { nome: "Sym",              subito: "sym",             autoscout: "sym",             motoIt: "sym" },
    { nome: "Triumph",          subito: "triumph",         autoscout: "triumph",         motoIt: "triumph" },
    { nome: "Vespa",            subito: "vespa",           autoscout: "piaggio",         motoIt: "vespa" },
    { nome: "Yamaha",           subito: "yamaha",          autoscout: "yamaha",          motoIt: "yamaha" },
    { nome: "Zero Motorcycles", subito: "zero-motorcycles",autoscout: "zero",            motoIt: "zero" },
  ]
};
